name: Build packages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [ published ]
  pull_request:

env:
  pydjinni__package__version: ${{ github.event.release.tag_name || '0.0.0' }}

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Set up Conan
        run: conan profile detect
      - name: Conan install
        run: conan install . --output-folder=build --build=missing
      - name: CMake configure (macOS, Linux)
        if: matrix.os != 'windows-latest'
        run: cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        working-directory: build
      - name: CMake configure (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake .. -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
        working-directory: build
      - name: CMake build (macOS, Linux)
        if: matrix.os != 'windows-latest'
        run: cmake --build . --target tests
        working-directory: build
      - name: CMake build (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build . --config Release --target tests
        working-directory: build
      - name: CTest
        run: ctest --output-on-failure
        working-directory: build
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            package: aar
            target: android
          - os: windows-latest
            package: nuget
            target: windows
          - os: windows-latest
            package: aar
            target: android
          - os: macos-latest
            package: aar
            target: android
          - os: macos-latest
            package: swiftpackage
            target: ios ios_simulator macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        if: matrix.target == 'android'
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        if: matrix.target == 'android'
        uses: gradle/actions/setup-gradle@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Set up Conan
        run: conan profile detect
      - name: Build Package
        run: pydjinni package ${{ matrix.package }} ${{ matrix.target }}
      - name: Publish Package
        if: github.event_name == 'release' && ( matrix.os == 'macos-latest' || (matrix.os == 'windows-latest' && matrix.package == 'nuget') )
        env:
          pydjinni__package__aar__publish__password: ${{ secrets.GITHUB_TOKEN }}
          pydjinni__package__nuget__publish__password: ${{ secrets.GITHUB_TOKEN }}
          pydjinni__package__swiftpackage__publish__password: ${{ secrets.SWIFTPACKAGE_PUBLISH_TOKEN }}
        run: pydjinni publish ${{ matrix.package }}
